"""empty message

Revision ID: 02ad5d8bb58a
Revises: 
Create Date: 2019-08-06 16:07:04.847568

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '02ad5d8bb58a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fin_cat', sa.Column('dup_desc', sa.String(length=250), nullable=False))
    op.add_column('fin_cat', sa.Column('fab_desc', sa.String(length=250), nullable=False))
    op.add_column('fin_cat', sa.Column('sal_desc', sa.String(length=250), nullable=False))
    op.add_column('fin_cat', sa.Column('top_desc', sa.String(length=250), nullable=False))
    op.drop_column('fin_cat', 'desc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fin_cat', sa.Column('desc', mysql.VARCHAR(length=250), nullable=False))
    op.drop_column('fin_cat', 'top_desc')
    op.drop_column('fin_cat', 'sal_desc')
    op.drop_column('fin_cat', 'fab_desc')
    op.drop_column('fin_cat', 'dup_desc')
    # ### end Alembic commands ###
