"""empty message

Revision ID: 17b805d7e8a5
Revises: a8b413b448f8
Create Date: 2019-06-21 15:51:21.891948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17b805d7e8a5'
down_revision = 'a8b413b448f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fin_goods', sa.Column('gen_name', sa.String(length=50), nullable=True))
    op.add_column('raw_fab_main', sa.Column('gen_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_fab_main', 'gen_name')
    op.drop_column('fin_goods', 'gen_name')
    # ### end Alembic commands ###
