"""empty message

Revision ID: 5bb096c1b9c1
Revises: 02ad5d8bb58a
Create Date: 2019-08-06 16:15:04.690777

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5bb096c1b9c1'
down_revision = '02ad5d8bb58a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fab_comb', sa.Column('dup_desc', sa.String(length=250), nullable=False))
    op.add_column('fab_comb', sa.Column('fab_desc', sa.String(length=250), nullable=False))
    op.add_column('fab_comb', sa.Column('sal_desc', sa.String(length=250), nullable=False))
    op.add_column('fab_comb', sa.Column('top_desc', sa.String(length=250), nullable=False))
    op.drop_column('fab_comb', 'desc')
    op.add_column('fin_cat', sa.Column('desc', sa.String(length=250), nullable=False))
    op.drop_column('fin_cat', 'fab_desc')
    op.drop_column('fin_cat', 'top_desc')
    op.drop_column('fin_cat', 'sal_desc')
    op.drop_column('fin_cat', 'dup_desc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fin_cat', sa.Column('dup_desc', mysql.VARCHAR(length=250), nullable=False))
    op.add_column('fin_cat', sa.Column('sal_desc', mysql.VARCHAR(length=250), nullable=False))
    op.add_column('fin_cat', sa.Column('top_desc', mysql.VARCHAR(length=250), nullable=False))
    op.add_column('fin_cat', sa.Column('fab_desc', mysql.VARCHAR(length=250), nullable=False))
    op.drop_column('fin_cat', 'desc')
    op.add_column('fab_comb', sa.Column('desc', mysql.VARCHAR(length=250), nullable=False))
    op.drop_column('fab_comb', 'top_desc')
    op.drop_column('fab_comb', 'sal_desc')
    op.drop_column('fab_comb', 'fab_desc')
    op.drop_column('fab_comb', 'dup_desc')
    # ### end Alembic commands ###
