"""empty message

Revision ID: 7fa999ba7cfa
Revises: c5a3ec5da275
Create Date: 2019-07-17 16:24:47.356596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fa999ba7cfa'
down_revision = 'c5a3ec5da275'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uom_acc',
    sa.Column('uom_id', sa.Integer(), nullable=True),
    sa.Column('acc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['acc_id'], ['accessories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uom_id'], ['uom.id'], ondelete='SET NULL')
    )
    op.create_table('uom_oth',
    sa.Column('uom_id', sa.Integer(), nullable=True),
    sa.Column('mat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mat_id'], ['other_mat.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uom_id'], ['uom.id'], ondelete='SET NULL')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uom_oth')
    op.drop_table('uom_acc')
    # ### end Alembic commands ###
