"""empty message

Revision ID: b900491819c3
Revises: 658ea43d873c
Create Date: 2019-06-18 16:37:44.343899

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b900491819c3'
down_revision = '658ea43d873c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', mysql.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
