"""empty message

Revision ID: c5a3ec5da275
Revises: 
Create Date: 2019-07-02 14:02:09.058674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5a3ec5da275'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trans', sa.Column('flag', sa.Integer(), nullable=True))
    op.add_column('trans', sa.Column('meta', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trans', 'meta')
    op.drop_column('trans', 'flag')
    # ### end Alembic commands ###
